_base_: ../_base_/default.yaml

train:
  batch_size: 128
  accumulation: 1

env:
  name: mmrb
  skill_init: reflact/envs/mmrb/skills/initial.md
  split_mode: ratio
  split_ratio: "2:1:7"
  split_dir: ""
  data_path: ""
  split_output_dir: ""
  max_turns: 1
  workers: 16
  limit: 0
  image_detail: auto
